Models/AppSetting.cs
using System.ComponentModel.DataAnnotations;

namespace ShopDienThoai.Models
{
    public class AppSetting
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string ShortDesc { get; set; }
        public string Logo { get; set; }
        public string Icon { get; set; }

        [Required(ErrorMessage = "Chọn vai trò mặc định cho người dùng!")]
        public string DefaultRoleId { get; set; }
    }
}

Models/EditCarouselViewModel.cs
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;

namespace ShopDienThoai.Models
{
    public class EditCarouselViewModel
    {
        public IEnumerable<IFormFile> ImageFiles { get; set; }
    }
}

ViewModels/AppSettingViewModel.cs
using Microsoft.AspNetCore.Http;
using ShopDienThoai.Models.Validation;
using System.ComponentModel.DataAnnotations;

namespace ShopDienThoai.ViewModels
{
    public class AppSettingViewModel
    {
        [Required(ErrorMessage = "Nhập vào tên trang web!")]
        [StringLength(30, MinimumLength = 5)]
        public string Title { get; set; }

        [StringLength(100, MinimumLength = 5)] public string ShortDesc { get; set; }

        public string Logo { get; set; }
        public string Icon { get; set; }

        [DataType(DataType.Upload)]
        [AllowedExtensions(new[] { ".jpg", ".png" })]
        [MaxFileSize(1 * 1024 * 1024)]
        public IFormFile LogoFile { get; set; }

        [DataType(DataType.Upload)]
        [AllowedExtensions(new[] { ".jpg", ".png" })]
        [MaxFileSize(1 * 1024 * 1024)]
        public IFormFile IconFile { get; set; }

        [Required(ErrorMessage = "Chọn vai trò mặc định cho người dùng!")]
        public string DefaultRoleId { get; set; }
    }
}

Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using ShopDienThoai.Models;
using ShopDienThoai.ViewModels;
using System;
using System.IO;
using System.Linq;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ShopDienThoai.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DashboardController : Controller
    {
        private readonly ICarouselImageRepository carouselImageRepository;
        private readonly AppDbContext context;
        private readonly IWebHostEnvironment webHostEnvironment;

        public DashboardController(IWebHostEnvironment webHostEnvironment, AppDbContext context,
            ICarouselImageRepository carouselImageRepository)
        {
            this.webHostEnvironment = webHostEnvironment;
            this.context = context;
            this.carouselImageRepository = carouselImageRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AppSetting()
        {
            var appSetting = (from s in context.AppSettings
                              select new AppSettingViewModel
                              {
                                  Icon = s.Icon,
                                  Logo = s.Logo,
                                  ShortDesc = s.ShortDesc,
                                  Title = s.Title,
                                  DefaultRoleId = s.DefaultRoleId
                              }).ToList().FirstOrDefault();
            ViewBag.Roles = (from r in context.Roles select r).ToList();
            return View(appSetting);
        }

        [HttpPost]
        public IActionResult AppSetting(AppSettingViewModel model)
        {
            if (ModelState.IsValid)
            {
                var setting = context.AppSettings.FirstOrDefault();
                setting.Title = model.Title;
                setting.ShortDesc = model.ShortDesc;
                if (model.LogoFile != null)
                {
                    var uploadFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                    var fileName = $"{Guid.NewGuid()}{Path.GetExtension(model.LogoFile.FileName)}";
                    var filePath = Path.Combine(uploadFolder, fileName);
                    using var fs = new FileStream(filePath, FileMode.Create);
                    model.LogoFile.CopyTo(fs);

                    setting.Logo = fileName;
                    if (!string.IsNullOrEmpty(model.Logo))
                    {
                        var delFile = Path.Combine(webHostEnvironment.WebRootPath, "images", model.Logo);
                        System.IO.File.Delete(delFile);
                    }
                }

                if (model.IconFile != null)
                {
                    var uploadFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                    var fileName = $"{Guid.NewGuid()}{Path.GetExtension(model.IconFile.FileName)}";
                    var filePath = Path.Combine(uploadFolder, fileName);
                    using var fs = new FileStream(filePath, FileMode.Create);
                    model.IconFile.CopyTo(fs);

                    setting.Icon = fileName;
                    if (!string.IsNullOrEmpty(model.Icon))
                    {
                        var delFile = Path.Combine(webHostEnvironment.WebRootPath, "images", model.Icon);
                        System.IO.File.Delete(delFile);
                    }
                }

                setting.DefaultRoleId = model.DefaultRoleId;
                context.SaveChanges();
                return RedirectToAction("AppSetting");
            }

            return View();
        }

        public IActionResult RemoveCarouselImage(int id)
        {
            _ = carouselImageRepository.Remove(id);
            return RedirectToAction("EditCarousel");
        }

        [HttpGet]
        public IActionResult EditCarousel()
        {
            ViewBag.Images = carouselImageRepository.Get();
            return View();
        }

        [HttpPost]
        public IActionResult EditCarousel(EditCarouselViewModel model)
        {
            if (model.ImageFiles != null)
            {
                var uploadFolder = Path.Combine(webHostEnvironment.WebRootPath, "images\\carousel");
                foreach (var imageFile in model.ImageFiles)
                {
                    var fileName = $"{Guid.NewGuid()}{Path.GetExtension(imageFile.FileName)}";
                    var filePath = Path.Combine(uploadFolder, fileName);
                    using var fs = new FileStream(filePath, FileMode.Create);
                    imageFile.CopyTo(fs);

                    carouselImageRepository.Create(new CarouselImage
                    {
                        Name = fileName
                    });
                }
            }

            return RedirectToAction("EditCarousel");
        }
    }
}

Views/Dashboard/AppSetting.cshtml
@model AppSettingViewModel
@{
    ViewBag.Title = "Cài đặt trang web";
    var roles = ViewBag.Roles as List<IdentityRole>;
}

<form enctype="multipart/form-data" asp-controller="Dashboard" asp-action="AppSetting" method="post">
    <input asp-for="Logo" value="@Model.Logo" hidden />
    <input asp-for="Icon" value="@Model.Icon" hidden />
    <div class="row form-group">
        <div class="col-md-3">
        </div>
        <div class="col-md-9">
            <img id="logoImage" src="@(!string.IsNullOrEmpty(Model.Logo) ? $"/images/{Model.Logo}" : "/images/0.png")" width="150" style="display: none;" class="mx-auto d-block my-3" asp-append-version="true" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-3">
            <label asp-for="LogoFile">Logo: </label>
        </div>
        <div class="col-md-9">
            <input type="file" class="custom-file-input selectImage mx-1" asp-for="LogoFile" id="i_file1">
            <label class="custom-file-label selectImage mx-2" asp-for="LogoFile">Đổi Logo</label>
            <span asp-validation-for="LogoFile" class="text-danger"></span>
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-3">
        </div>
        <div class="col-md-9">
            <img id="iconImage" src="@(!string.IsNullOrEmpty(Model.Logo) ? $"/images/{Model.Icon}" : "/images/0.png")" width="150" style="display: none;" class="mx-auto d-block my-3" asp-append-version="true" />
        </div>
    </div>

    <div class="row form-group">
        <div class="col-md-3">
            <label asp-for="IconFile">Icon: </label>
        </div>
        <div class="col-md-9">
            <input type="file" class="custom-file-input selectImage mx-1" asp-for="IconFile" id="i_file2">
            <label class="custom-file-label selectImage mx-2" asp-for="IconFile">Đổi Icon</label>
            <span asp-validation-for="IconFile" class="text-danger"></span>
        </div>
    </div>

    <div class="row form-group">
        <div class="col-md-3">
            <label asp-for="Title">Tên trang web: </label>
        </div>
        <div class="col-md-9">
            <input asp-for="Title" class="form-control" placeholder="Nhập tên trang web">
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
    </div>

    <div class="row form-group">
        <div class="col-md-3">
            <label asp-for="ShortDesc">Mô tả ngắn: </label>
        </div>
        <div class="col-md-9">
            <input asp-for="ShortDesc" class="form-control" placeholder="Nhập mô tả ngắn về trang web">
            <span asp-validation-for="ShortDesc" class="text-danger"></span>
        </div>
    </div>

    <div class="row form-group">
        <div class="col-md-3">
            <label asp-for="DefaultRoleId">Vai trò người dùng mặc định: </label>
        </div>
        <div class="col-md-9">
            <select asp-for="DefaultRoleId" class="custom-select">
                <option value="">Chọn vai trò mặc định</option>
                @foreach (var role in roles)
                {
                    <option value="@role.Id">@role.Name</option>
                }
            </select>
            <span asp-validation-for="DefaultRoleId" class="text-danger"></span>
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-3">
        </div>
        <div class="col-md-9">
            <button type="submit" class="btn btn-primary">Lưu</button>
            <a asp-controller="Dashboard" asp-action="Index" class="btn btn-secondary">Huỷ</a>
        </div>
    </div>
</form>

@section scripts
{
    <environment include="Development">
        <script src="~/lib/jquery-validate/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.2/dist/jquery.validate.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
    </environment>
    <script>
        $(".custom-file-input").on("change",
            function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
            });
        $('#i_file1').change(function (event) {
            $("#logoImage").fadeIn("fast").attr('src', URL.createObjectURL(event.target.files[0]));
        });
        $('#i_file2').change(function (event) {
            $("#iconImage").fadeIn("fast").attr('src', URL.createObjectURL(event.target.files[0]));
        });
    </script>
}

Views/Dashboard/EditCarousel.cshtml
@model EditCarouselViewModel
@{
    ViewBag.Title = "Cài đặt Slide";
    var images = ViewBag.Images as IEnumerable<CarouselImage>;
}
<form enctype="multipart/form-data" asp-controller="Dashboard" asp-action="EditCarousel" method="post">
    <div class="row form-group">
        <div class="col-md-3">
        </div>
        <div class="col-md-9">
            @if (images != null)
            {
                @foreach (var image in images)
                 {
                     <img src="~/images/carousel/@image.Name" height="200" class="mx-1 my-1" />
                     <a class="remove-image" asp-controller="Dashboard" asp-action="RemoveCarouselImage" asp-route-id="@image.Id" style="display: inline;">&#215;</a>
                 }
            }
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-3">
        </div>
        <div class="col-md-9 gallery">
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-3">
            <label asp-for="ImageFiles">Ảnh slide: </label>
        </div>
        <div class="col-md-9">
            <div class="custom-file">
                <input type="file" class="custom-file-input selectImage" asp-for="ImageFiles" id="i_file" multiple>
                <label class="custom-file-label selectImage" asp-for="ImageFiles">Chọn ảnh</label>
            </div>
            <span asp-validation-for="ImageFiles" class="text-danger"></span>
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-3">
        </div>
        <div class="col-md-9">
            <button type="submit" class="btn btn-primary">Lưu</button>
            <a asp-controller="Dashboard" asp-action="Index" class="btn btn-secondary">Huỷ</a>
        </div>
    </div>
</form>

@section scripts{
    <script>
        $(function() {
            var imagesPreview = function(input, placeToInsertImagePreview) {
                if (input.files) {
                    var filesAmount = input.files.length;
                    for (i = 0; i < filesAmount; i++) {
                        var reader = new FileReader();
                        reader.onload = function(event) {
                            $($.parseHTML('<img>')).attr('src', event.target.result).attr('height', '200px')
                                .attr('class', 'mx-1 my-1').appendTo(placeToInsertImagePreview);
                        };
                        reader.readAsDataURL(input.files[i]);
                    }
                }
            };

            $('#i_file').on('change',
                function() {
                    $("div.gallery").empty();
                    imagesPreview(this, 'div.gallery');
                    var fileLabel = $(this).next('.custom-file-label');
                    var files = $(this)[0].files;
                    if (files.length > 1) {
                        fileLabel.html(files.length + ' tập tin được chọn');
                    } else if (files.length == 1) {
                        fileLabel.html(files[0].name);
                    }
                });
        });
    </script>
}

@section styles{
    <style>
        .remove-image {
            -webkit-transition: background 0.5s;
            background: #555;
            border: 3px solid #fff;
            border-radius: 10em;
            box-shadow: 0 2px 6px rgba(0, 0, 0, 0.5), inset 0 2px 4px rgba(0, 0, 0, 0.3);
            color: #FFF;
            display: none;
            font: 700 21px/20px sans-serif;
            padding: 2px 6px 3px;
            position: absolute;
            text-decoration: none;
            text-shadow: 0 1px 2px rgba(0, 0, 0, 0.5);
            transition: background 0.5s;
        }

        .remove-image:hover {
            background: #E54E4E;
            padding: 3px 7px 5px;
        }

        .remove-image:active { background: #E54E4E; }
    </style>
}

Views/Dashboard/Index.cshtml
@{
    ViewBag.Title = "Trang quản trị";
}